var format = require('./index.js')
var assert = require('assert')

console.log('[+] Executing tests')
assert.equal("Forever {Python}".format({Python: "JavaScript"}), 'Forever JavaScript')
assert.equal("Forever {0}".format(["JavaScript"]), 'Forever JavaScript')
assert.equal("Forever {Java}".format({}, true), 'Forever ')
console.log('[+] 50% OK')
assert.equal(format("Forever {Python}", {Python: "JavaScript"}), 'Forever JavaScript')
assert.equal(format("Forever {0}", ["JavaScript"]), 'Forever JavaScript')
assert.equal(format("Forever {Java}", {}, true), 'Forever ')
console.log('[+] 100% OK')